package GUI;

import estructuras.ListaEstados;
import estructuras.ListaSimbolos;
import estructuras.ListaEstadosFinales;
import estructuras.NodoEstado;
import estructuras.ListaTransiciones;
import logica.DFA;
import logica.ValidadorDFA;
import estructuras.NodoSimbolo;

/**
 *
 * @author maria
 */
public class CrearDFA extends javax.swing.JFrame {

    private ListaEstados listaEstados = new ListaEstados();
    private ListaSimbolos listaSimbolos = new ListaSimbolos();
    private ListaEstadosFinales listaEstadosFinales = new ListaEstadosFinales();
    private ListaTransiciones listaTransiciones = new ListaTransiciones();
    private DFA dfa;
    private ValidadorDFA validador;
    private boolean dfaValidado;
    private MainWindow ventanaPrincipal;
    
    private void marcarComoNoValidado() {

        dfaValidado = false;
        btnGuardarDFA.setEnabled(false);
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearDFA.class.getName());

    /**
     * Creates new form CrearDFA
     */
    public CrearDFA(MainWindow ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        dfa = new DFA();
        validador = new ValidadorDFA();

        dfaValidado = false;
        btnGuardarDFA.setEnabled(false);
    }
    
    public CrearDFA(MainWindow ventanaPrincipal, DFA dfaBase) {

        initComponents();

        this.ventanaPrincipal = ventanaPrincipal;

        dfa = new DFA();
        validador = new ValidadorDFA();

        dfaValidado = false;
        btnGuardarDFA.setEnabled(false);

        NodoSimbolo actual = dfaBase.getSimbolos().getCabeza();

        while (actual != null) {

            listaSimbolos.insertar(actual.getSimbolo());
            dfa.agregarSimbolo(actual.getSimbolo());

            actual = actual.getSiguiente();
        }

        listaSimbolos.llenarCombo(cmbSimbolo);

        txtSimbolos.setText(
                listaSimbolos.obtenerTexto()
        );

        btnAgregarSimbolo.setEnabled(false);
        txtSimbolo.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAgregarEstado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEstados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSimbolo = new javax.swing.JTextField();
        btnAgregarSimbolo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSimbolos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstadoInicial = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEstadoFinal = new javax.swing.JTextField();
        btnMarcarFinal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEstadosFinales = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbSimbolo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        btnAgregarTransicion = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTransiciones = new javax.swing.JTextArea();
        btnGuardarDFA = new javax.swing.JButton();
        btnValidarDFA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel1.setText("ESTADOS");

        jLabel2.setText("Nombre del Estado:");

        btnAgregarEstado.setText("Agregar");
        btnAgregarEstado.addActionListener(this::btnAgregarEstadoActionPerformed);

        txtEstados.setColumns(20);
        txtEstados.setRows(5);
        jScrollPane2.setViewportView(txtEstados);

        jLabel3.setText("ALFABETO");

        jLabel4.setText("Simbolo:");

        txtSimbolo.addActionListener(this::txtSimboloActionPerformed);

        btnAgregarSimbolo.setText("Agregar");
        btnAgregarSimbolo.addActionListener(this::btnAgregarSimboloActionPerformed);

        txtSimbolos.setColumns(20);
        txtSimbolos.setRows(5);
        jScrollPane1.setViewportView(txtSimbolos);

        jLabel5.setText("ESTADO INICIAL");

        jLabel6.setText("Estado Inicial:");

        cmbEstadoInicial.addActionListener(this::cmbEstadoInicialActionPerformed);

        jLabel7.setText("ESTADOS FINALES");

        btnMarcarFinal.setText("Marcar como final");
        btnMarcarFinal.addActionListener(this::btnMarcarFinalActionPerformed);

        txtEstadosFinales.setColumns(20);
        txtEstadosFinales.setRows(5);
        jScrollPane3.setViewportView(txtEstadosFinales);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Crear DFA");

        jLabel9.setText("TRANSICIONES");

        jLabel10.setText("Estado origen:");

        cmbOrigen.addActionListener(this::cmbOrigenActionPerformed);

        jLabel11.setText("Símbolo:");

        cmbSimbolo.addActionListener(this::cmbSimboloActionPerformed);

        jLabel12.setText("Estado destino:");

        cmbDestino.addActionListener(this::cmbDestinoActionPerformed);

        btnAgregarTransicion.setText("Agregar transición");
        btnAgregarTransicion.addActionListener(this::btnAgregarTransicionActionPerformed);

        txtTransiciones.setColumns(20);
        txtTransiciones.setRows(5);
        jScrollPane4.setViewportView(txtTransiciones);

        btnGuardarDFA.setText("Crear DFA");
        btnGuardarDFA.addActionListener(this::btnGuardarDFAActionPerformed);

        btnValidarDFA.setText("Validar DFA");
        btnValidarDFA.addActionListener(this::btnValidarDFAActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregarEstado)
                                    .addComponent(btnAgregarSimbolo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEstadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMarcarFinal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(224, 224, 224)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardarDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnValidarDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAgregarTransicion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarSimbolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstadoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarcarFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnValidarDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarTransicion)
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstadoActionPerformed
        String nombre = txtEstado.getText().trim();

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un nombre para el estado."
            );
            return;
        }

        if (listaEstados.existe(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El estado '" + nombre + "' ya existe."
            );
            return;
        }

        listaEstados.insertar(nombre);

        dfa.agregarEstado(nombre);

        txtEstados.setText(listaEstados.obtenerTexto());

        listaEstados.llenarCombo(cmbEstadoInicial);
        listaEstados.llenarCombo(cmbOrigen);
        listaEstados.llenarCombo(cmbDestino);

        marcarComoNoValidado();
        
        txtEstado.setText("");
        txtEstado.requestFocus();
    }//GEN-LAST:event_btnAgregarEstadoActionPerformed

    private void btnAgregarSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSimboloActionPerformed
        String simbolo = txtSimbolo.getText().trim();

        if (simbolo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un símbolo."
            );
            return;
        }

        if (listaSimbolos.existe(simbolo)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El símbolo '" + simbolo + "' ya existe."
            );
            return;
        }

        listaSimbolos.insertar(simbolo);
        dfa.agregarSimbolo(simbolo);

        txtSimbolos.setText(listaSimbolos.obtenerTexto());
        listaSimbolos.llenarCombo(cmbSimbolo);

        marcarComoNoValidado();
        
        txtSimbolo.setText("");
        txtSimbolo.requestFocus();
    }//GEN-LAST:event_btnAgregarSimboloActionPerformed

    private void txtSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimboloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSimboloActionPerformed

    private void cmbEstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoInicialActionPerformed
       if (cmbEstadoInicial.getSelectedItem() != null) {

        String estadoInicial =
                cmbEstadoInicial.getSelectedItem().toString();

        dfa.setEstadoInicial(estadoInicial);
    }
    }//GEN-LAST:event_cmbEstadoInicialActionPerformed

    private void btnMarcarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarFinalActionPerformed
        String nombre = txtEstadoFinal.getText().trim();

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el nombre de un estado."
            );
            return;
        }

        if (!listaEstados.existe(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El estado '" + nombre + "' no existe."
            );
            return;
        }

        if (listaEstadosFinales.existe(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El estado '" + nombre + "' ya es final."
            );
            return;
        }

        NodoEstado actual = listaEstados.getCabeza();

        while (actual != null) {

            if (actual.getNombre().equals(nombre)) {
                listaEstadosFinales.insertar(actual);
                dfa.agregarEstadoFinal(nombre);
                break;
            }

            actual = actual.getSiguiente();
        }

        txtEstadosFinales.setText(
                listaEstadosFinales.obtenerTexto()
        );
        
        marcarComoNoValidado();

        txtEstadoFinal.setText("");
        txtEstadoFinal.requestFocus();
    }//GEN-LAST:event_btnMarcarFinalActionPerformed

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigenActionPerformed

    private void cmbSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSimboloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSimboloActionPerformed

    private void cmbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestinoActionPerformed

    private void btnAgregarTransicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTransicionActionPerformed
        if (cmbOrigen.getSelectedItem() == null) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe agregar estados primero."
        );

        return;
    }

    if (cmbSimbolo.getSelectedItem() == null) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe agregar símbolos primero."
        );

        return;
    }

    if (cmbDestino.getSelectedItem() == null) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe agregar estados primero."
        );

        return;
    }

    String origen =
            cmbOrigen.getSelectedItem().toString();

    String simbolo =
            cmbSimbolo.getSelectedItem().toString();

    String destino =
            cmbDestino.getSelectedItem().toString();

    if (listaTransiciones.existe(origen, simbolo)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ya existe una transición para "
                + "(" + origen + ", " + simbolo + ")."
        );

        return;
    }

    listaTransiciones.insertar(
            origen,
            simbolo,
            destino
        );

    dfa.agregarTransicion(
            origen,
            simbolo,
            destino
        );

    txtTransiciones.setText(
            listaTransiciones.obtenerTexto()
    );
    
    marcarComoNoValidado();
    }//GEN-LAST:event_btnAgregarTransicionActionPerformed

    private void btnValidarDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarDFAActionPerformed
        String resultado = validador.validar(dfa);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                resultado
        );

        if (resultado.equals("DFA válido.")) {

            dfaValidado = true;
            btnGuardarDFA.setEnabled(true);

}    }//GEN-LAST:event_btnValidarDFAActionPerformed

    private void btnGuardarDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDFAActionPerformed
         if (!dfaValidado) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe validar el DFA antes de guardarlo."
        );

        return;
    }

    ventanaPrincipal.guardarDFA(dfa);

    dispose();
    }//GEN-LAST:event_btnGuardarDFAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainWindow ventana = new MainWindow();
            ventana.setVisible(true);
        });
    }
    
    public DFA getDFA() {
    return dfa;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstado;
    private javax.swing.JButton btnAgregarSimbolo;
    private javax.swing.JButton btnAgregarTransicion;
    private javax.swing.JButton btnGuardarDFA;
    private javax.swing.JButton btnMarcarFinal;
    private javax.swing.JButton btnValidarDFA;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbEstadoInicial;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbSimbolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtEstadoFinal;
    private javax.swing.JTextArea txtEstados;
    private javax.swing.JTextArea txtEstadosFinales;
    private javax.swing.JTextField txtSimbolo;
    private javax.swing.JTextArea txtSimbolos;
    private javax.swing.JTextArea txtTransiciones;
    // End of variables declaration//GEN-END:variables
}
