/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import estructuras.ListaEstados;
import estructuras.ListaSimbolos;

/**
 *
 * @author maria
 */
public class CrearDFA extends javax.swing.JFrame {

    private ListaEstados listaEstados = new ListaEstados();
    private ListaSimbolos listaSimbolos = new ListaSimbolos();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearDFA.class.getName());

    /**
     * Creates new form CrearDFA
     */
    public CrearDFA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAgregarEstado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEstados = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSimbolo = new javax.swing.JTextField();
        btnAgregarSimbolo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSimbolos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 650));

        jLabel1.setText("ESTADOS");

        jLabel2.setText("Nombre del Estado:");

        btnAgregarEstado.setText("Agregar");
        btnAgregarEstado.addActionListener(this::btnAgregarEstadoActionPerformed);

        txtEstados.setColumns(20);
        txtEstados.setRows(5);
        jScrollPane2.setViewportView(txtEstados);

        jLabel3.setText("ALFABETO");

        jLabel4.setText("Simbolo:");

        txtSimbolo.addActionListener(this::txtSimboloActionPerformed);

        btnAgregarSimbolo.setText("Agregar");
        btnAgregarSimbolo.addActionListener(this::btnAgregarSimboloActionPerformed);

        txtSimbolos.setColumns(20);
        txtSimbolos.setRows(5);
        jScrollPane1.setViewportView(txtSimbolos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEstado)
                                    .addComponent(txtSimbolo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarEstado)
                            .addComponent(btnAgregarSimbolo)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarSimbolo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstadoActionPerformed
        String nombre = txtEstado.getText().trim();

        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un nombre para el estado."
            );
            return;
        }

        if (listaEstados.existe(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El estado '" + nombre + "' ya existe."
            );
            return;
        }

        listaEstados.insertar(nombre);

        txtEstados.setText(listaEstados.obtenerTexto());

        txtEstado.setText("");
        txtEstado.requestFocus();
    }//GEN-LAST:event_btnAgregarEstadoActionPerformed

    private void btnAgregarSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSimboloActionPerformed
        String simbolo = txtSimbolo.getText().trim();

        if (simbolo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese un símbolo."
            );
            return;
        }

        if (listaSimbolos.existe(simbolo)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El símbolo '" + simbolo + "' ya existe."
            );
            return;
        }

        listaSimbolos.insertar(simbolo);

        txtSimbolo.setText(listaSimbolos.obtenerTexto());

        txtSimbolo.setText("");
        txtSimbolo.requestFocus();
    }//GEN-LAST:event_btnAgregarSimboloActionPerformed

    private void txtSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimboloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearDFA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstado;
    private javax.swing.JButton btnAgregarSimbolo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextArea txtEstados;
    private javax.swing.JTextField txtSimbolo;
    private javax.swing.JTextArea txtSimbolos;
    // End of variables declaration//GEN-END:variables
}
