package GUI;

/**
 *
 * @author maria
 */

import logica.DFA;
import GUI.CrearDFA;
import logica.UnionDFA;
import logica.ProbadorCadena;

public class MainWindow extends javax.swing.JFrame {
  
    private DFA dfa1;
    private DFA dfa2;
    private DFA dfaUnion;
    private ProbadorCadena probador;
    
    public void guardarDFA(DFA nuevoDFA) {

        if (dfa1 == null) {

            dfa1 = nuevoDFA;

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "DFA 1 guardado correctamente."
            );

        } else if (dfa2 == null) {

            dfa2 = nuevoDFA;

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "DFA 2 guardado correctamente."
            );

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ya existen dos DFA guardados."
            );

            return;
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        dfa1 = null;
        dfa2 = null;
        dfaUnion = null;
        probador = new ProbadorCadena();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrearDFA = new javax.swing.JButton();
        btnUnionDFA = new javax.swing.JButton();
        btnProbarCadena = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de DFA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de DFA");

        btnCrearDFA.setText("Crear DFA");
        btnCrearDFA.setToolTipText("");
        btnCrearDFA.addActionListener(this::btnCrearDFAActionPerformed);

        btnUnionDFA.setText("Union DFA");
        btnUnionDFA.addActionListener(this::btnUnionDFAActionPerformed);

        btnProbarCadena.setText("Probar Cadena");
        btnProbarCadena.setToolTipText("");
        btnProbarCadena.addActionListener(this::btnProbarCadenaActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearDFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnionDFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProbarCadena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnUnionDFA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProbarCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCrearDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDFAActionPerformed
        CrearDFA ventana;

        if (dfa1 == null) {
            ventana = new CrearDFA(this);
        } else if (dfa2 == null) {
            ventana = new CrearDFA(this, dfa1);
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ya existen dos DFA guardados."
            );
            return;
        }

        ventana.setVisible(true);
    }//GEN-LAST:event_btnCrearDFAActionPerformed

    private void btnUnionDFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionDFAActionPerformed
        if (dfa1 == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Debe crear y guardar el DFA 1 primero."
            );

            return;
        }

        if (dfa2 == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Debe crear y guardar el DFA 2 primero."
            );

            return;
        }

        UnionDFA unionDFA = new UnionDFA();

        DFA resultado
                = unionDFA.unir(dfa1, dfa2);

        if (resultado == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se puede realizar la unión: "
                    + "los DFA tienen alfabetos diferentes."
            );

            return;
        }

        dfaUnion = resultado;

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unión de DFA creada correctamente."
        );
    }//GEN-LAST:event_btnUnionDFAActionPerformed

    private boolean probarCadena(DFA dfa, String cadena) {

        if (dfa == null) {
            return false;
        }

        String estadoActual
                = dfa.getEstadoInicial();

        for (int i = 0; i < cadena.length(); i++) {

            String simbolo
                    = String.valueOf(cadena.charAt(i));

            if (!dfa.getSimbolos().existe(simbolo)) {
                return false;
            }

            String siguiente
                    = null;

            estructuras.NodoTransicion transicion
                    = dfa.getTransiciones().getCabeza();

            while (transicion != null) {

                if (transicion.getOrigen().equals(estadoActual)
                        && transicion.getSimbolo().equals(simbolo)) {

                    siguiente
                            = transicion.getDestino();

                    break;
                }

                transicion
                        = transicion.getSiguiente();
            }

            if (siguiente == null) {
                return false;
            }

            estadoActual = siguiente;
        }

        return dfa.getEstadosFinales().existe(
                estadoActual
        );
    }
    
    private void btnProbarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarCadenaActionPerformed
        if (dfa1 == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Debe crear y guardar el DFA 1 primero."
            );

            return;
        }

        String[] opciones;

        if (dfaUnion != null) {

            opciones = new String[]{
                "DFA 1",
                "DFA 2",
                "Unión DFA"
            };

        } else if (dfa2 != null) {

            opciones = new String[]{
                "DFA 1",
                "DFA 2"
            };

        } else {

            opciones = new String[]{
                "DFA 1"
            };
        }

        String seleccion
                = (String) javax.swing.JOptionPane.showInputDialog(
                        this,
                        "Seleccione el DFA:",
                        "Probar Cadena",
                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                        null,
                        opciones,
                        opciones[0]
                );

        if (seleccion == null) {
            return;
        }

        String cadena
                = javax.swing.JOptionPane.showInputDialog(
                        this,
                        "Ingrese la cadena:"
                );

        if (cadena == null) {
            return;
        }

        DFA dfaSeleccionado;

        if (seleccion.equals("DFA 1")) {

            dfaSeleccionado = dfa1;

        } else if (seleccion.equals("DFA 2")) {

            dfaSeleccionado = dfa2;

        } else {

            dfaSeleccionado = dfaUnion;
        }

        boolean aceptada
                = probador.probar(
                        dfaSeleccionado,
                        cadena
                );

        String recorrido
                = probador.obtenerRecorrido(
                        dfaSeleccionado,
                        cadena
                );

        if (aceptada) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Cadena: " + cadena
                    + "\n\n"
                    + "Recorrido:\n"
                    + recorrido
                    + "\n\n"
                    + "RESULTADO: ACEPTADA"
            );

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Cadena: " + cadena
                    + "\n\n"
                    + "Recorrido:\n"
                    + recorrido
                    + "\n\n"
                    + "RESULTADO: RECHAZADA"
            );
        }
     }//GEN-LAST:event_btnProbarCadenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearDFA;
    private javax.swing.JButton btnProbarCadena;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnionDFA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
